#IPQ LPASS SND CARD

obj-y += ipq806x.o

snd-soc-ipq806x-dai-objs := ipq-cpu-dai.o
snd-soc-ipq806x-dmlite-objs := ipq-dmlite.o
snd-soc-ipq806x-lpaif-objs := ipq-lpaif.o
snd-soc-ipq806x-pcm-objs := ipq-pcm-voip.o

obj-y +=ipq-pcm-mi2s.o
obj-y +=ipq-pcm-spdif.o
obj-y +=ipq-spdif.o
obj-y +=ipq-lpass-codec.o

obj-y += snd-soc-ipq806x-pcm.o snd-soc-ipq806x-dai.o snd-soc-ipq806x-dmlite.o snd-soc-ipq806x-lpaif.o snd-soc-ipq806x-pcm.o
