/* ADSS AUDIO Registers */

#define ADSS_BASE 	0x7700000
#define ADSS_RANGE 	0x20000

/* ADSS_AUDIO_LOCAL_REG	Registers */

#define ADSS_GLB_PCM_RST_REG		0x0

#define ADSS_GLB_PCM_MBOX_CTRL_REG	0x0C

#define ADSS_GLB_CHIP_CTRL_I2S_REG		0x10
#define GLB_CHIP_CTRL_I2S_INTERFACE_EN		(1 << 0)
#define GLB_CHIP_CTRL_I2S_STEREO0_GLB_EN	(1 << 1)
#define GLB_CHIP_CTRL_I2S_STEREO1_GLB_EN	(1 << 2)
#define GLB_CHIP_CTRL_I2S_STEREO2_GLB_EN	(1 << 3)

#define ADSS_GLB_I2S_RST_REG		0x14

#define ADSS_GLB_CLK_I2S_CTRL_REG	0x18
#define GLB_CLK_I2S_CTRL_TX_BCLK_OE	(1 << 28)
#define GLB_CLK_I2S_CTRL_RX_BCLK_OE	(1 << 27)
#define GLB_CLK_I2S_CTRL_RX_MCLK_OE	(1 << 16)
#define GLB_CLK_I2S_CTRL_TX_MCLK_OE	(1 << 17)

#define ADSS_GLB_TDM_CTRL_REG		0x1C

#define ADSS_GLB_PWM0_CTRL_REG		0x20

#define ADSS_GLB_PWM1_CTRL_REG		0x24

#define ADSS_GLB_PWM2_CTRL_REG		0x28

#define ADSS_GLB_PWM3_CTRL_REG		0x2C

#define ADSS_GLB_AUDIO_MODE_REG		0x30
#define GLB_AUDIO_MODE_RECV_I2S		(0 << 2)
#define GLB_AUDIO_MODE_RECV_TDM		(1 << 2)
#define GLB_AUDIO_MODE_XMIT_I2S		(0 << 0)
#define GLB_AUDIO_MODE_XMIT_TDM		(1 << 0)
#define GLB_AUDIO_MODE_I2S0_TXD_OE	(7 << 4)
#define GLB_AUDIO_MODE_I2S0_FS_OE	(1 << 7)
#define GLB_AUDIO_MODE_I2S3_FS_OE	(1 << 8)
#define GLB_AUDIO_MODE_I2S3_RXD_OE	(1 << 9)
#define GLB_AUDIO_MODE_SPDIF_OUT_OE	(1 << 10)
#define GLB_AUDIO_MODE_I2S0_RD_SWAP	(0 << 16)
#define GLB_AUDIO_MODE_I2S0_WR_SWAP 	(0 << 17)
#define GLB_AUDIO_MODE_I2S1_RD_SWAP	(0 << 18)
#define GLB_AUDIO_MODE_I2S1_WR_SWAP	(0 << 19)
#define GLB_AUDIO_MODE_I2S2_RD_SWAP	(0 << 20)
#define GLB_AUDIO_MODE_I2S2_WR_SWAP	(0 << 21)
#define GLB_AUDIO_MODE_I2S3_RD_SWAP	(0 << 22)
#define GLB_AUDIO_MODE_I2S3_WR_SWAP	(0 << 23)
#define GLB_AUDIO_MODE_B1K		(1 << 28)

#define ADSS_GLB_AUDIO_MODE2_REG	0x34

#define ADSS_AUDIO_PLL_CONFIG_REG	0x38
#define AUDIO_PLL_CONFIG_REFDIV(x)	(x << 0)
#define AUDIO_PLL_CONFIG_PLLPWD		(0 << 5)
#define AUDIO_PLL_CONFIG_POSTPLLDIV(x)	(x << 7)

#define ADSS_AUDIO_PLL_MODULATION_REG		0x3C
#define AUDIO_PLL_MODULATION_TGT_DIV_INT(x)	(x << 9)
#define AUDIO_PLL_MODULATION_TGT_DIV_FRAC(x)	(x << 11)

#define ADSS_AUDIO_PLL_MOD_STEP_REG		0x40

#define ADSS_CURRENT_AUDIO_PLL_MODULATION_REG	0x44

#define ADSS_AUDIO_PLL_CONFIG1_REG		0x48

#define ADSS_AUDIO_ATB_SETTING_REG		0x4C

#define ADSS_AUDIO_RXB_CFG_MUXR_REG		0x104
#define AUDIO_RXB_CFG_MUXR_SRC_SEL(x)		(x << 8)

#define ADSS_AUDIO_RXB_MISC_REG			0x108
#define AUDIO_RXB_MISC_AUTO_SCALE_DIV(x)	(x << 1)

#define ADSS_AUDIO_RXB_CBCR_REG			0x10C

#define ADSS_AUDIO_RXM_CMD_RCGR_REG		0x120
#define AUDIO_RXM_CMD_RCGR_UPDATE		(1 << 0)
#define AUDIO_RXM_CMD_RCGR_ROOT_EN		(1 << 1)

#define ADSS_AUDIO_RXM_CFG_RCGR_REG		0x124
#define AUDIO_RXM_CFG_RCGR_SRC_DIV(x)		(x << 4)
#define AUDIO_RXM_CFG_RCGR_SRC_SEL(x)		(x << 8)

#define ADSS_AUDIO_RXM_MISC_REG			0x128

#define ADSS_AUDIO_RXM_CBCR_REG			0x12C

#define ADSS_AUDIO_TXB_CFG_MUXR_REG		0x144
#define AUDIO_TXB_CFG_MUXR_SRC_SEL(x)		(x << 8)

#define ADSS_AUDIO_TXB_MISC_REG			0x148

#define ADSS_AUDIO_TXB_CBCR_REG			0x14C

#define ADSS_AUDIO_SPDIF_MISC_REG		0x150

#define ADSS_AUDIO_SPDIF_CBCR_REG		0x154

#define ADSS_AUDIO_SPDIFDIV2_MISC_REG		0x158

#define ADSS_AUDIO_SPDIFDIV2_CBCR_REG		0x15C

#define ADSS_AUDIO_TXM_CMD_RCGR_REG		0x160
#define AUDIO_TXM_CMD_RCGR_ROOT_EN		(1 << 1)
#define AUDIO_TXM_CMD_RCGR_UPDATE		(1 << 0)

#define ADSS_AUDIO_TXM_CFG_RCGR_REG		0x164
#define AUDIO_TXM_CFG_RCGR_SRC_DIV(x)		(x << 0)
#define AUDIO_TXM_CFG_RCGR_SRC_SEL(x)		(x << 8)

#define ADSS_AUDIO_TXM_MISC_REG			0x168
#define AUDIO_TXM_MISC_AUTO_SCALE_DIV(x)	(x << 4)

#define ADSS_AUDIO_TXM_CBCR_REG			0x16C

#define ADSS_AUDIO_SAMPLE_CBCR_REG		0x18C

#define ADSS_AUDIO_PCM_CMD_RCGR_REG		0x1A0

#define ADSS_AUDIO_PCM_CFG_RCGR_REG		0x1A4

#define ADSS_AUDIO_PCM_MISC_REG			0x1A8

#define ADSS_AUDIO_PCM_CBCR_REG			0x1AC

#define ADSS_AUDIO_XO_CBCR_REG			0x1CC

#define ADSS_AUDIO_SPDIFINFAST_CMD_RCGR_REG	0x1E0

#define ADSS_AUDIO_SPDIFINFAST_CFG_RCGR_REG	0x1E4

#define ADSS_AUDIO_SPDIFINFAST_CBCR_REG		0x1EC

#define ADSS_AUDIO_AHB_CBCR_REG			0x200

#define ADSS_AUDIO_AHB_I2S0_CBCR_REG		0x204

#define ADSS_AUDIO_AHB_I2S3_CBCR_REG		0x208

#define ADSS_AUDIO_AHB_MBOX0_CBCR_REG		0x20C

#define DSS_AUDIO_AHB_MBOX3_CBCR_REG		0x210

/* WL_DPLL_REG Registers*/

#define WL_DPLL_REG_BASE	ADSS_BASE + 0x2000

#define ADPLL1_BANK_REG		WL_DPLL_REG_BASE + 0x440

#define ADPLL2_BANK_REG		WL_DPLL_REG_BASE + 0x444

#define ADPLL3_BANK_REG		WL_DPLL_REG_BASE + 0x448

#define ADPLL4_BANK_REG		WL_DPLL_REG_BASE + 0x44C

#define ADPLL5_BANK_REG		WL_DPLL_REG_BASE + 0x450

/* ADSS_AUDIO_PCM_REG Registers */

#define ADSS_AUDIO_PCM_REG_BASE 	ADSS_BASE + 0x4000

#define AADSS_PCM_BITMAP_REG		ADSS_AUDIO_PCM_REG_BASE + 0x0

#define AADSS_PCM_CTRL_REG		ADSS_AUDIO_PCM_REG_BASE + 0x04

#define AADSS_PCM_OFFSET_REG		ADSS_AUDIO_PCM_REG_BASE + 0x08

#define AADSS_PCM_START_REG		ADSS_AUDIO_PCM_REG_BASE + 0x0C

#define AADSS_PCM_INT_STATUS_REG	ADSS_AUDIO_PCM_REG_BASE + 0x10

#define AADSS_PCM_INT_ENABLE_REG	ADSS_AUDIO_PCM_REG_BASE + 0x14

#define AADSS_PCM_RX_DATA_8BIT_REG	ADSS_AUDIO_PCM_REG_BASE + 0x18

#define AADSS_PCM_TX_DATA_8BIT_REG	ADSS_AUDIO_PCM_REG_BASE + 0x1C

#define AADSS_PCM_DIVIDER_REG		ADSS_AUDIO_PCM_REG_BASE + 0x20

#define AADSS_PCM_TH_REG		ADSS_AUDIO_PCM_REG_BASE + 0x24

#define AADSS_PCM_FIFO_CNT_REG		ADSS_AUDIO_PCM_REG_BASE + 0x28

#define AADSS_PCM_FIFO_ERR_SLOT_REG	ADSS_AUDIO_PCM_REG_BASE + 0x2C

#define AADSS_PCM_RX_DATA_16BIT_REG	ADSS_AUDIO_PCM_REG_BASE + 0x30

#define AADSS_PCM_TX_DATA_16BIT_REG	ADSS_AUDIO_PCM_REG_BASE + 0x34


/* ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG Registers */

#define ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE	ADSS_BASE + 0x6000

#define AADSS_MBOXSPDIFIN_MBOX_FIFO0_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x0

#define AADSS_MBOXSPDIFIN_MBOX_FIFO_STATUS0_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x08

#define AADSS_MBOXSPDIFIN_MBOX_DMA_POLICY_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x10

#define AADSS_MBOXSPDIFIN_MBOX0_DMA_RX_DESCRIPTOR_BASE_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x18

#define AADSS_MBOXSPDIFIN_MBOX0_DMA_RX_CONTROL_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x1C

#define AADSS_MBOXSPDIFIN_MBOX0_DMA_TX_DESCRIPTOR_BASE_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x20

#define AADSS_MBOXSPDIFIN_MBOX0_DMA_TX_CONTROL_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x24

#define AADSS_MBOXSPDIFIN_MBOX_FRAME_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x38

#define AADSS_MBOXSPDIFIN_FIFO_TIMEOUT_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x40

#define AADSS_MBOXSPDIFIN_MBOX_INT_STATUS_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x44

#define AADSS_MBOXSPDIFIN_MBOX_INT_ENABLE_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x4C

#define AADSS_MBOXSPDIFIN_MBOX_FIFO_RESET_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x58

#define AADSS_MBOXSPDIFIN_MBOX_DEBUG_CHAIN0_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x60

#define AADSS_MBOXSPDIFIN_MBOX_DEBUG_CHAIN1_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x64

#define AADSS_MBOXSPDIFIN_MBOX_DEBUG_CHAIN0_SIGNALS_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x68

#define AADSS_MBOXSPDIFIN_MBOX_DEBUG_CHAIN1_SIGNALS_REG \\
	ADSS_MBOXSPDIFIN_AUDIO_MBOX_REG_BASE + 0x6C

/* Registers */

#define ADSS_MBOX_STEREO_AUDIO_BASE			ADSS_BASE + 0x8000

#define ADSS_MBOX0_AUDIO_BASE 				0x0 /* ADSS_MBOX_STEREO_AUDIO_BASE + 0x0 */
#define ADSS_MBOX1_AUDIO_BASE 				0x2000
#define ADSS_MBOX2_AUDIO_BASE 				0x4000
#define ADSS_MBOX3_AUDIO_BASE 				0x6000

#define ADSS_MBOXn_MBOX_FIFO0_REG			0x0
#define MBOX_FIFO_RESET_TX_INIT				(1 << 0)
#define MBOX_FIFO_RESET_RX_INIT				(1 << 2)

#define ADSS_MBOXn_MBOX_FIFO_STATUS0_REG		0x08

#define ADSS_MBOXn_MBOX_DMA_POLICY_REG			0x10
#define MBOX_DMA_POLICY_SW_RESET			(1 << 31)
#define MBOX_DMA_POLICY_TX_INT_TYPE			(1 << 17)
#define MBOX_DMA_POLICY_RX_INT_TYPE			(1 << 16)
#define ADSS_MBOX_DMA_POLICY_SRAM_AC(x)         	(((x >> 28) & 0xf) << 12)
#define ADSS_MBOX_DMA_POLICY_TX_FIFO_THRESHOLD(x)	(((x & 0xf) << 4))



#define ADSS_MBOXn_MBOXn_DMA_RX_DESCRIPTOR_BASE_REG	0x18

#define ADSS_MBOXn_MBOXn_DMA_RX_CONTROL_REG		0x1C
#define ADSS_MBOXn_DMA_RX_CONTROL_STOP			(1 << 0)
#define ADSS_MBOXn_DMA_RX_CONTROL_START			(1 << 1)
#define ADSS_MBOXn_DMA_RX_CONTROL_RESUME		(1 << 2)


#define ADSS_MBOXn_MBOXn_DMA_TX_DESCRIPTOR_BASE_REG	0x20

#define ADSS_MBOXn_MBOXn_DMA_TX_CONTROL_REG		0x24
#define ADSS_MBOXn_DMA_TX_CONTROL_STOP                  (1 << 0)
#define ADSS_MBOXn_DMA_TX_CONTROL_START                 (1 << 1)
#define ADSS_MBOXn_DMA_TX_CONTROL_RESUME                (1 << 2)



#define ADSS_MBOXn_MBOX_FRAME_REG			0x38

#define ADSS_MBOXn_FIFO_TIMEOUT_REG			0x40

#define ADSS_MBOXn_MBOX_INT_STATUS_REG			0x44
#define MBOX_INT_STATUS_TX_DMA_COMPLETE			(1 << 6)
#define MBOX_INT_STATUS_RX_DMA_COMPLETE			(1 << 10)

#define ADSS_MBOXn_MBOX_INT_ENABLE_REG			0x4C
#define MBOX_INT_ENABLE_RX_DMA_COMPLETE			(1 << 10)
#define MBOX_INT_STATUS_RX_UNDERFLOW			(1 << 4)
#define MBOX_INT_STATUS_RX_FIFO_UNDERFLOW		(1 << 12)
#define MBOX_INT_ENABLE_TX_DMA_COMPLETE			(1 << 6)
#define MBOX_INT_STATUS_TX_OVERFLOW			(1 << 5)
#define MBOX_INT_STATUS_TX_FIFO_OVERFLOW		(1 << 13)


#define ADSS_MBOXn_MBOX_FIFO_RESET_REG			0x58
#define MBOX_FIFO_RESET_TX_INIT				(1 << 0)
#define MBOX_FIFO_RESET_RX_INIT				(1 << 2)

#define ADSS_MBOXn_MBOX_DEBUG_CHAIN0_REG		0x60

#define ADSS_MBOXn_MBOX_DEBUG_CHAIN1_REG		0x64

#define ADSS_MBOXn_MBOX_DEBUG_CHAIN0_SIGNALS_REG	0x68

#define ADSS_MBOXn_MBOX_DEBUG_CHAIN1_SIGNALS_REG	0x6C

/* ADSS_STEREO0_AUDIO_STEREO_REG Registers */

#define ADSS_STEREO0_AUDIO_BASE		0x1000 /* ADSS_MBOX_STEREO_AUDIO_BASE + 0x1000 */
#define ADSS_STEREO1_AUDIO_BASE		0x3000
#define ADSS_STEREO2_AUDIO_BASE		0x5000
#define ADSS_STEREO3_AUDIO_BASE		0x7000

#define ADSS_STEREOn_STEREO0_CONFIG_REG			0x0
#define STEREOn_CONFIG_MCK_SEL				(0 << 10)
#define STEREOn_CONFIG_MASTER				(1 << 8)
#define STEREOn_CONFIG_DATA_WORD_SIZE(x)		(x << 12)
#define STEREOn_CONFIG_DATA_WORD_SIZE_MASK		(3 << 12)
#define STEREOn_CONFIG_I2S_WORD_SIZE_32			(1 << 11)
#define STEREOn_CONFIG_MIC_WORD_SIZE			(1 << 16)
#define STEREOn_CONFIG_I2S_DELAY			(0 << 18)
#define STEREOn_CONFIG_MIC_SWAP				(0 << 24)
#define STEREOn_CONFIG_ENABLE				(1 << 21)
#define STEREOn_CONFIG_MIC_RESET			(1 << 20)
#define STEREOn_CONFIG_RESET				(1 << 19)
#define STEREOn_CONFIG_SPDIF_ENABLE			(1 << 23)
#define STEREOn_CONFIG_SAMPLE_CNT_CLEAR_TYPE		(1 << 9)
#define STEREOn_CONFIG_PCM_SWAP				(1 << 17)

#define AADSS_STEREOn_STEREO0_VOLUME_REG(n)		0x04

#define AADSS_STEREOn_STEREO_MASTER_CLOCK_REG(n)	0x08

#define AADSS_STEREOn_STEREO0_TX_SAMPLE_CNT_LSB_REG(n)	0x0C

#define AADSS_STEREOn_STEREO0_TX_SAMPLE_CNT_MSB_REG(n)	0x10

#define AADSS_STEREOn_STEREO0_RX_SAMPLE_CNT_LSB_REG(n)	0x14

#define AADSS_STEREOn_STEREO0_RX_SAMPLE_CNT_MSB_REG(n)	0x18

#define AADSS_STEREOn_STEREO0_UNDERRUN_CNT_REG(n)	0x1C

#define AADSS_STEREOn_STEREO0_OVERRUN_CNT_REG(n)	0x20

#define AADSS_STEREOn_STEREO0_TX_COMPLETE_CNT_REG(n)	0x24

#define AADSS_STEREOn_STEREO0_RX_COMPLETE_CNT_REG(n)	0x28


/* Configs */
#define ADSS_MBOX_IRQ                           (156 + 32)


extern void __iomem *adss_audio_local_base;
extern void __iomem *adss_stereo0_reg_base;
extern void __iomem *mbox0_reg_base;
