# SPDX-License-Identifier: GPL-2.0

qnoc-sdm845-objs			:= sdm845.o
icc-rpmh-obj			:= icc-rpmh.o

obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o
